# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ stable_test ]
  pull_request:
    branches: [ stable_test ]

jobs:
  test:
    strategy:
      matrix:
        platform: [ macos-latest ]
        node-version: [ 12.x ]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - name: test importWithAuthenticateUsernamePassword.test
      run: npm run test src/tests/importWithOption/importWithAuthenticateUsernamePassword.test.js
